"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
from glob import glob

PACKAGES = ['pyobjc', 'paho-mqtt', 'keyring']
APP_NAME = "mqtt2notification"
APP = ['mqtt2mac.py']
DATA_FILES = glob("resources/*.xib") + glob("resources/*.png")
OPTIONS = { 
  'iconfile':'resources/main.icns',
  'plist': {
    'CFBundleName': APP_NAME,
    'LSUIElement': '1',
    'CFBundleDisplayName': APP_NAME,
    'CFBundleGetInfoString': "Display notifications using mqtt",
    'CFBundleIdentifier': "com.macbury.mqtt2notification",
    'CFBundleVersion': "0.2.0",
    'NSUserNotificationAlertStyle': "alert",
    'NSPrincipalClass': 'NSApplication'
  }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
